#!/usr/bin/env python3
"""
build-skills-index.py — generate a compact, tiered catalog of Hermes skills
so the agent never loads the whole library into context.

Outputs:
  <skills>/index.yaml          root tree: top-level skills + category entries
  <category>/index.yaml        per-category listings (category subfolders)

Protocol for the agent (see SOUL.md):
  1. read index.yaml first (small);
  2. open the matching category index only when relevant;
  3. load a single SKILL.md only when its description/tags match the task.

Usage:
  build-skills-index.py [--skills DIR]      (default: ~/.hermes/skills)
"""

from __future__ import annotations

import argparse
import datetime as _dt
import re
from pathlib import Path


def parse_frontmatter(path: Path) -> dict:
    """Extract name/description/tags/cwe_ids from a SKILL.md front-matter block."""
    try:
        text = path.read_text(encoding="utf-8-sig", errors="replace")
    except OSError:
        return {}
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.S)
    if not m:
        return {}
    block = m.group(1)
    out: dict = {"tags": [], "cwe": []}
    key = None
    for raw in block.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("- "):
            if key in ("tags", "cwe"):
                out[key].append(line[2:].strip().strip('"'))
            continue
        km = re.match(r"^([A-Za-z_]+):\s*(.*)$", line)
        if not km:
            continue
        key = km.group(1)
        val = km.group(2).strip().strip('"').strip("'")
        if key == "name":
            out["name"] = val
        elif key == "description":
            out["description"] = val
        elif key == "tags":
            out["tags"] = []
        elif key == "cwe_ids":
            out["cwe"] = []
        elif key == "cwe" and val:
            out["cwe"].append(val)
    return out


def yaml_str(v: str) -> str:
    v = v.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{v}"'


def count_skills(d: Path) -> int:
    return sum(1 for _ in d.rglob("SKILL.md"))


def category_description(cat: Path) -> str:
    """First heading of the category README, or a generic fallback."""
    readme = cat / "README.md"
    if readme.is_file():
        try:
            for raw in readme.read_text(encoding="utf-8-sig", errors="replace").splitlines():
                if raw.startswith("#"):
                    return raw.lstrip("# ").strip()
        except OSError:
            pass
    return "Imported skill library — browse its index on demand"


def build_category_index(cat: Path) -> str:
    """One-line-per-skill index for a category folder (immediate skills only)."""
    lines = [
        f"# {cat.name} — {count_skills(cat)} skills",
        "# Load a SKILL.md only when its description/tags match the task.",
    ]
    for child in sorted(cat.iterdir()):
        if not child.is_dir():
            continue
        md = child / "SKILL.md"
        if not md.is_file():
            lines.append(f"{child.name}:")
            lines.append(f"  description: {yaml_str(category_description(child))}")
            lines.append("  nested: true  # contains sub-skills; list the folder on demand")
            continue
        fm = parse_frontmatter(md)
        desc = fm.get("description") or "no description"
        tags = fm.get("tags") or []
        cwe = fm.get("cwe") or []
        nested = count_skills(child) > 1
        lines.append(f"{child.name}:")
        lines.append(f"  description: {yaml_str(desc)}")
        if tags:
            lines.append(f"  tags: [{', '.join(yaml_str(t) for t in tags)}]")
        if cwe:
            lines.append(f"  cwe: [{', '.join(yaml_str(c) for c in cwe)}]")
        lines.append(f"  file: {child.name}/SKILL.md")
        if nested:
            lines.append("  nested: true  # contains sub-skills; list the folder on demand")
    return "\n".join(lines) + "\n"


def build_root_index(skills: Path) -> str:
    total = count_skills(skills)
    lines = [
        "# HERMES SKILLS CATALOG — auto-generated by build-skills-index.py",
        "# Protocol: never preload skill files. Read this tree, then open the",
        "# matching SKILL.md only. Regenerate after adding skills.",
        f"generated: {_dt.date.today().isoformat()}",
        f"total_skills: {total}",
        "skills:",
    ]
    for child in sorted(skills.iterdir()):
        if not child.is_dir():
            continue
        md = child / "SKILL.md"
        if md.is_file():
            fm = parse_frontmatter(md)
            lines.append(f"  {child.name}:")
            lines.append(f"    description: {yaml_str(fm.get('description') or 'no description')}")
            lines.append(f"    file: {child.name}/SKILL.md")
    categories = [
        child
        for child in sorted(skills.iterdir())
        if child.is_dir() and not (child / "SKILL.md").is_file()
    ]
    if categories:
        lines.append("categories:")
    for child in sorted(skills.iterdir()):
        if not child.is_dir() or (child / "SKILL.md").is_file():
            continue  # real skill folders appear in `skills:` above
        n = count_skills(child)
        lines.append(f"  {child.name}:")
        lines.append(f"    description: {yaml_str(category_description(child))}")
        lines.append(f"    count: {n}")
        lines.append(f"    index: {child.name}/index.yaml")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the Hermes skills catalog")
    parser.add_argument("--skills", default=str(Path.home() / ".hermes" / "skills"))
    args = parser.parse_args()
    skills = Path(args.skills)
    if not skills.is_dir():
        raise SystemExit(f"skills dir not found: {skills}")

    (skills / "index.yaml").write_text(build_root_index(skills), encoding="utf-8")
    for child in sorted(skills.iterdir()):
        if child.is_dir() and not (child / "SKILL.md").is_file():
            (child / "index.yaml").write_text(
                build_category_index(child), encoding="utf-8"
            )
    print(f"catalog written under {skills}")


if __name__ == "__main__":
    main()
