#!/usr/bin/env bash
# toolkit-scan.sh — regenerate ~/.hermes/toolkit/inventory.yaml
# Dynamic catalog: tools on PATH + key files (masked). Never edit inventory.yaml by hand.
set -uo pipefail

TK="${HOME}/.hermes/toolkit"
OUT="${TK}/inventory.yaml"
NOW="$(date +%Y-%m-%dT%H:%M:%S%z 2>/dev/null || date -Iseconds 2>/dev/null || date)"

mask() { # mask <secret> -> first4...last4 (or *** if short)
  local s="$1" n="${#1}"
  s="${s%"${s##*[![:space:]]}"}"   # strip trailing whitespace
  n="${#s}"
  if [ "$n" -le 8 ]; then printf '***'; return; fi
  printf '%s...%s' "${s:0:4}" "${s: -4}"
}

mkdir -p "${TK}/keys"

{
  printf '# Auto-generated by toolkit-scan.sh — do not edit manually.\n'
  printf 'generated_at: "%s"\n\n' "$NOW"

  printf 'tools:\n'
  for t in nuclei subfinder httpx nmap sqlmap wpscan nikto gobuster ffuf whatweb droopescan drupwn ngrok openvpn jq curl python3; do
    p="$(command -v "$t" 2>/dev/null || true)"
    if [ -n "$p" ]; then
      v="$("$t" --version 2>/dev/null | grep -Ev '^[[:space:]_]*$' | head -1 || true)"
      printf '  %s:\n    path: "%s"\n    version: "%s"\n' "$t" "$p" "$v"
    fi
  done
  if [ -d "${HOME}/nuclei-templates" ]; then
    printf '  nuclei_templates:\n    path: "%s"\n    templates: "%s"\n' \
      "${HOME}/nuclei-templates" \
      "$(find "${HOME}/nuclei-templates" -name '*.yaml' 2>/dev/null | wc -l)"
  fi

  printf '\nkeys:\n'
  check_key() { # check_key <name> <path> [extract-mode]
    local name="$1" path="$2" mode="${3:-raw}" v=""
    if [ -f "$path" ]; then
      case "$mode" in
        wpscan)  v="$(grep -o '"api_token":"[^"]*"' "$path" 2>/dev/null | head -1 | sed 's/.*"api_token":"//; s/"//')" ;;
        ngrok)   v="$(grep -o 'authtoken:.*' "$path" 2>/dev/null | head -1 | sed 's/authtoken:[[:space:]]*//')" ;;
        config)  v="(configured)" ;;
        *)       v="$(head -c 256 "$path" 2>/dev/null | tr '\n' ' ')" ;;
      esac
      printf '  %s:\n    path: "%s"\n    status: present\n' "$name" "$path"
      if [ "$v" = "(configured)" ]; then
        printf '    masked: "(configured)"\n'
      else
        printf '    masked: "%s"\n' "$(mask "$v")"
      fi
    else
      printf '  %s:\n    status: missing\n' "$name"
    fi
  }
  check_key vulners   "${HOME}/.config/vulners/api.key"
  check_key nvd       "${HOME}/.config/nvd/api.key"
  check_key wpscan    "${HOME}/.wpscan/scan.json" wpscan
  check_key ngrok     "${HOME}/.config/ngrok/ngrok.yml" ngrok
  check_key subfinder "${HOME}/.config/subfinder/provider-config.yaml" config
  check_key uncover   "${HOME}/.config/uncover/provider-config.yaml" config
  check_key vpn_user  "${HOME}/.hermes/toolkit/keys/vpn_user.key" config
  check_key vpn_pass  "${HOME}/.hermes/toolkit/keys/vpn_pass.key" config

  printf '\nextra_keys:\n'
  found=0
  for f in "${TK}"/keys/*; do
    [ -e "$f" ] || continue
    found=1
    printf '  - file: "%s"\n    masked: "%s"\n' "$f" "$(mask "$(head -c 128 "$f" | tr '\n' ' ')")"
  done
  [ "$found" = 0 ] && printf '  []\n'

  printf '\nvpn_profiles:\n'
  mapfile -t PROFILES < <(find "${HOME}/vpn-profiles" -name '*.ovpn' 2>/dev/null | sort)
  cnt="${#PROFILES[@]}"
  printf '  count: "%s"\n' "$cnt"
  if [ "$cnt" -gt 0 ]; then
    printf '  files:\n'
    for f in "${PROFILES[@]}"; do
      printf '    - "%s"\n' "${f#"${HOME}/"}"
    done
  fi

  printf '\nassets:\n'
  if [ -d "${TK}/assets" ]; then
    mapfile -t AS < <(find "${TK}/assets" -maxdepth 1 -type f ! -name manifest.json 2>/dev/null | sort)
    if [ "${#AS[@]}" -gt 0 ]; then
      for f in "${AS[@]}"; do
        printf '  - "%s"\n' "${f#"${TK}/"}"
      done
    else
      printf '  []\n'
    fi
  else
    printf '  []\n'
  fi

  printf '\nnotes: |\n  Run this script after installing a tool or adding a key.\n  The agent reads this file first whenever it needs tools or keys.\n'
} > "$OUT"

chmod 600 "$OUT"
echo "inventory written: $OUT"
